# 関数内で定義された変数に関数外からアクセスすると例外(エラー)が発生する
if x > 100:
    print("x is > 100")
